apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/base
- github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac
- github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac
- templates.yaml
patchesStrategicMerge:
- config.yaml
namespace: argo
